---
image: elixir:latest

services:
- postgres:latest

cache:
  paths:
  - _build/
  - deps/

variables:
  MIX_ENV: test
  DATABASE_URL: postgres://postgres@postgres:5432/alloy_ci_test

before_script:
- mix local.hex --force
- mix local.rebar --force
- mix deps.get
- mix ecto.setup

mix:
  stage: test
  tags:
  - elixir
  - postgres
  script:
  - mix test

credo:
  stage: test
  tags:
  - elixir
  script:
  - mix credo
